apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-statefulset-demo-2
  labels:
    type: MyApp
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
