apiVersion: v1
kind: Service
metadata:
  name: statefulset-demo-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
spec:
  selector:
    matchLabels:
      app: MyApp
  serviceName: statefulset-demo-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
        - name: stateful-set-container
          image: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: pvc
              mountPath: "/var/www/html"
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: ""  # Important: leave empty to match manually created PVs
